name: 'HULL & STERN'
favicon: null
layout_spectrum: 0.48905
typography_spectrum: 0.74568
title: 'HULL & STERN'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f3543'
    - '#eaebc9'
    - '#4ebac4'
    - '#f86b4f'
    - '#028d70'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
