name: hullstern
favicon: null
layout_spectrum: 0.2889914836268872
typography_spectrum: 0.6506202830933034
title: 'HULL & STERN'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f3543'
    - '#eaebc9'
    - '#4ebac4'
    - '#f86b4f'
    - '#028d70'
  brandStrength: 0.8508287316653877
  lightness: 0.12060281098820269
  saturation: 0.782139404444024
  rhythmicContrast: 0.986662206472829
purpose: []
